### ISSUE TITLE
The python catwalk client does not offer the option to change the max_n_positions option

### ISSUE THREAD

**Issue by davidhwyllie** [dvolk/catwalk#2]
The python catwalk client does not currently offer the option to change the max_n_positions option on server startup.

**Comment by davidhwyllie** [comment]
This is in fact a limitation of catwalk at present.

The catwalk server was uses a hard coded max_n_positions of 130,000 and ? a hard coded max_snp of 20 

This is set from 
c.settings.max_n_positions
line 70
https://github.com/dvolk/catwalk/blob/master/src/cw_server.nim

and does not appear to be configurable.
Samples are rejected if > this number of Ns
https://github.com/dvolk/catwalk/blob/master/src/catwalk.nim line 108

but this cannot be customised (is this right?) as it is not a parameter of the Catwalk object
https://github.com/dvolk/catwalk/blob/master/src/catwalk.nim line 35

but instead is hard coded (along with max_distance)
see https://github.com/dvolk/catwalk/blob/master/src/catwalk.nim line 137,139

The 130k figure and 20 SNP are appropriate for TB as we currently process it but might not be for other organisms such as NTMs.
We need to be able to pass these as parameters to 
new_catwalk and to control these by the 
./cw_server compiled application setting these via the command line.

**Comment by dvolk** [comment]
Fixed in ec1e3f2 - removed max_distance and added max_n_positions
This means that invoking cw_server with --max_distance isn't possible any more. 
--max_n_positions is optional, the default is 130000.
the pycw_client, the /neighbours default distance isn't max_distance any more, but 99. A warning is issued when using the default distance.
