### ISSUE TITLE
The max_n_storage option does not behave as expected

### ISSUE THREAD

**Issue by davidhwyllie** [dvolk/catwalk#4]
What is the expected result if a sample is added with more unknown bases than max_n_storage?

I understood that the expected result was:  
- neighbours were not reported
- sample was marked 'highN' cf. https://github.com/dvolk/catwalk/blob/master/src/catwalk.nim line 106

How is this dealt with by process_neighbours (line 138 ff?) (is it?)
How is this dealt with by the api - how is 'highN' returned?

Unit tests of the expected behaviour fail, see test_cw_function.test_cw_4

**Comment by davidhwyllie** [comment]
Unit test is in branch test_cw_function

**Comment by dvolk** [comment]
Good spot. Fixed in 278b729.
